# Generated by Django 5.2.7 on 2026-06-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_order_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_status',
            field=models.CharField(choices=[('Not Applicable', 'Not Applicable'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='Not Applicable', max_length=20),
        ),
    ]
