# Generated by Django 5.2.7 on 2026-07-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_cart_id_alter_cartitem_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='refund_status',
            field=models.CharField(choices=[('Not Applicable', 'Not Applicable'), ('Pending', 'Pending'), ('Refund Initiated', 'Refund Initiated'), ('Refunded', 'Refunded'), ('Rejected', 'Rejected')], default='Not Applicable', max_length=20),
        ),
    ]
